main: top.penowl.quidproquo.QuidProQuo
name: QuidProQuo
version: 0.1
commands:
  ritual:
    description: Check ritual information.
    aliases: [quidproquo, rt]
    permission: quidproquo.command
    permission-message: You do not have /&lt;permission&gt;
    usage: |
      ยง3/ritual list [page] - List all available rituals.
      ยง3/ritual <ritual> - See the information on a ritual